@startuml flow
!theme crt-amber

participant User
participant Orchestrator
participant CSVReader
participant TXTReader
participant PDFWriter
participant FrontPage

User         -> Orchestrator: CSV (ID, artist, title,\ncapo transpose, comment)
User         -> Orchestrator: source txt directory
Orchestrator -> CSVReader   : CSV
CSVReader    -> Orchestrator: DataFrame
Orchestrator -> TXTReader   : DataFrame
TXTReader    -> Orchestrator: DataFrame with string column
Orchestrator -> PDFWriter   : DataFrame
PDFWriter    -> FrontPage   : DataFrame
FrontPage    -> PDFWriter   : front page
loop DataFrame
    PDFWriter    -> Song2Page   : Series
    Song2Page    -> PDFWriter   : song page
end
PDFWriter    -> User        : PDF

@enduml