@startuml flow
!theme crt-amber

participant User
participant Orchestrator
participant CSVReader
participant ThreadManager
participant Browser
participant TXTWriter

User         -> Orchestrator : CSV (ID, URL, browse transpose)
User         -> Orchestrator : destination txt directory
Orchestrator -> CSVReader    : CSV
CSVReader    -> Orchestrator : DataFrame
Orchestrator -> ThreadManager: DataFrame
loop DataFrame
    ThreadManager -> Browser      : Series
    Browser       -> ThreadManager: Series with string column
end
ThreadManager -> Orchestrator: DataFrame with string column
loop DataFrame
    Orchestrator -> TXTWriter: Series' string
    TXTWriter    -> User     : dest/dir/ID.txt
end

@enduml